import os
from attrdict import AttrDict

from utils import read_yaml

neptune_config = read_yaml('neptune_config.yaml')

X_COLUMNS = ['comment_text']
Y_COLUMNS = ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']

SOLUTION_CONFIG = AttrDict({
    'env': {'cache_dirpath': neptune_config.parameters.experiment_dir},
    'fill_na': {'na_columns': X_COLUMNS},
    'xy_split': {'x_columns': X_COLUMNS,
                 'y_columns': Y_COLUMNS
                 },
    'char_tokenizer': {'char_level': True,
                       'maxlen': neptune_config.parameters.maxlen_char,
                       'num_words': neptune_config.parameters.max_features_char
                       },
    'word_tokenizer': {'char_level': False,
                       'maxlen': neptune_config.parameters.maxlen_words,
                       'num_words': neptune_config.parameters.max_features_word
                       },
    'tfidf_char_vectorizer': {'sublinear_tf': True,
                              'strip_accents': 'unicode',
                              'analyzer': 'char',
                              'token_pattern': r'\w{1,}',
                              'ngram_range': (1, neptune_config.parameters.char_ngram_max),
                              'max_features': neptune_config.parameters.max_features_char
                              },
    'tfidf_word_vectorizer': {'sublinear_tf': True,
                              'strip_accents': 'unicode',
                              'analyzer': 'word',
                              'token_pattern': r'\w{1,}',
                              'ngram_range': (1, 1),
                              'max_features': neptune_config.parameters.max_features_word
                              },
    'glove_embeddings': {'pretrained_filepath': neptune_config.parameters.embedding_filepath,
                         'max_features': neptune_config.parameters.max_features_word,
                         'embedding_size': neptune_config.parameters.word_embedding_size
                         },
    'glove_dpcnn_network': {
        'architecture_config': {'model_params': {'max_features': neptune_config.parameters.max_features_word,
                                                 'maxlen': neptune_config.parameters.maxlen_words,
                                                 'embedding_size': neptune_config.parameters.word_embedding_size,
                                                 'trainable_embedding': neptune_config.parameters.trainable_embedding,
                                                 'filter_nr': neptune_config.parameters.dpcnn_filter_nr,
                                                 'kernel_size': neptune_config.parameters.dpcnn_kernel_size,
                                                 'repeat_block': neptune_config.parameters.dpcnn_repeat_block,
                                                 'dense_size': neptune_config.parameters.dpcnn_dense_size,
                                                 'repeat_dense': neptune_config.parameters.dpcnn_repeat_dense,
                                                 'l2_reg': neptune_config.parameters.l2_reg_convo,
                                                 'use_prelu': neptune_config.parameters.use_prelu,
                                                 'dropout_convo': neptune_config.parameters.dropout_convo,
                                                 'dropout_dense': neptune_config.parameters.dropout_dense
                                                 },
                                'optimizer_params': {'lr': neptune_config.parameters.lr,
                                                     'momentum': neptune_config.parameters.momentum,
                                                     'nesterov': True
                                                     },
                                },
        'training_config': {'epochs': neptune_config.parameters.epochs_nr,
                            'shuffle': True,
                            'batch_size': neptune_config.parameters.batch_size_train,
                            },
        'callbacks_config': {'model_checkpoint': {
            'filepath': os.path.join(neptune_config.parameters.experiment_dir, 'checkpoints',
                                     'glove_dpcnn_network',
                                     'glove_dpcnn_network.h5'),
            'save_best_only': True,
            'save_weights_only': False},
            'lr_scheduler': {'gamma': neptune_config.parameters.gamma},
            'early_stopping': {'patience': neptune_config.parameters.patience},
            'neptune_monitor': {},
        },
    },
    'glove_scnn_network': {
        'architecture_config': {'model_params': {'max_features': neptune_config.parameters.max_features_word,
                                                 'maxlen': neptune_config.parameters.maxlen_words,
                                                 'embedding_size': neptune_config.parameters.word_embedding_size,
                                                 'trainable_embedding': neptune_config.parameters.trainable_embedding,
                                                 'filter_nr': neptune_config.parameters.scnn_filter_nr,
                                                 'kernel_size': neptune_config.parameters.scnn_kernel_size,
                                                 'dense_size': neptune_config.parameters.scnn_dense_size,
                                                 'repeat_dense': neptune_config.parameters.scnn_repeat_dense,
                                                 'l2_reg': neptune_config.parameters.l2_reg_convo,
                                                 'use_prelu': neptune_config.parameters.use_prelu,
                                                 'dropout_convo': neptune_config.parameters.dropout_convo,
                                                 'dropout_dense': neptune_config.parameters.dropout_dense
                                                 },
                                'optimizer_params': {'lr': neptune_config.parameters.lr,
                                                     'momentum': neptune_config.parameters.momentum,
                                                     'nesterov': True
                                                     },
                                },
        'training_config': {'epochs': neptune_config.parameters.epochs_nr,
                            'shuffle': True,
                            'batch_size': neptune_config.parameters.batch_size_train,
                            },
        'callbacks_config': {'model_checkpoint': {
            'filepath': os.path.join(neptune_config.parameters.experiment_dir, 'checkpoints',
                                     'glove_scnn_network',
                                     'glove_scnn_network.h5'),
            'save_best_only': True,
            'save_weights_only': False},
            'lr_scheduler': {'gamma': neptune_config.parameters.gamma},
            'early_stopping': {'patience': neptune_config.parameters.patience},
            'neptune_monitor': {},
        },
    },
    'glove_lstm_network': {
        'architecture_config': {'model_params': {'max_features': neptune_config.parameters.max_features_word,
                                                 'maxlen': neptune_config.parameters.maxlen_words,
                                                 'embedding_size': neptune_config.parameters.word_embedding_size,
                                                 'trainable_embedding': neptune_config.parameters.trainable_embedding,
                                                 'unit_nr': neptune_config.parameters.lstm_unit_nr,
                                                 'repeat_block': neptune_config.parameters.lstm_repeat_block,
                                                 'global_pooling': neptune_config.parameters.global_pooling,
                                                 'dense_size': neptune_config.parameters.lstm_dense_size,
                                                 'repeat_dense': neptune_config.parameters.lstm_repeat_dense,
                                                 'l2_reg': neptune_config.parameters.l2_reg_convo,
                                                 'use_prelu': neptune_config.parameters.use_prelu,
                                                 'dropout_lstm': neptune_config.parameters.dropout_lstm,
                                                 'dropout_dense': neptune_config.parameters.dropout_dense
                                                 },
                                'optimizer_params': {'lr': neptune_config.parameters.lr,
                                                     },
                                },
        'training_config': {'epochs': neptune_config.parameters.epochs_nr,
                            'batch_size': neptune_config.parameters.batch_size_train,
                            },
        'callbacks_config': {'model_checkpoint': {
            'filepath': os.path.join(neptune_config.parameters.experiment_dir, 'checkpoints',
                                     'glove_lstm_network',
                                     'glove_lstm_network.h5'),
            'save_best_only': True,
            'save_weights_only': False},
            'lr_scheduler': {'gamma': neptune_config.parameters.gamma},
            'early_stopping': {'patience': neptune_config.parameters.patience},
            'neptune_monitor': {},
        },
    },
    'word_lstm_network': {
        'architecture_config': {'model_params': {'max_features': neptune_config.parameters.max_features_word,
                                                 'maxlen': neptune_config.parameters.maxlen_words,
                                                 'embedding_size': neptune_config.parameters.word_embedding_size,
                                                 'trainable_embedding': neptune_config.parameters.trainable_embedding,
                                                 'unit_nr': neptune_config.parameters.lstm_unit_nr,
                                                 'repeat_block': neptune_config.parameters.lstm_repeat_block,
                                                 'global_pooling': neptune_config.parameters.global_pooling,
                                                 'dense_size': neptune_config.parameters.lstm_dense_size,
                                                 'repeat_dense': neptune_config.parameters.lstm_repeat_dense,
                                                 'l2_reg': neptune_config.parameters.l2_reg_convo,
                                                 'use_prelu': neptune_config.parameters.use_prelu,
                                                 'dropout_lstm': neptune_config.parameters.dropout_lstm,
                                                 'dropout_dense': neptune_config.parameters.dropout_dense
                                                 },
                                'optimizer_params': {'lr': neptune_config.parameters.lr,
                                                     },
                                },
        'training_config': {'epochs': neptune_config.parameters.epochs_nr,
                            'batch_size': neptune_config.parameters.batch_size_train,
                            },
        'callbacks_config': {'model_checkpoint': {
            'filepath': os.path.join(neptune_config.parameters.experiment_dir, 'checkpoints', 'word_lstm_network',
                                     'word_lstm_network.h5'),
            'save_best_only': True,
            'save_weights_only': False},
            'lr_scheduler': {'gamma': neptune_config.parameters.gamma},
            'early_stopping': {'patience': neptune_config.parameters.patience},
            'neptune_monitor': {},
        },
    },
    'word_dpcnn_network': {
        'architecture_config': {'model_params': {'max_features': neptune_config.parameters.max_features_word,
                                                 'maxlen': neptune_config.parameters.maxlen_words,
                                                 'embedding_size': neptune_config.parameters.word_embedding_size,
                                                 'trainable_embedding': neptune_config.parameters.trainable_embedding,
                                                 'filter_nr': neptune_config.parameters.dpcnn_filter_nr,
                                                 'kernel_size': neptune_config.parameters.dpcnn_kernel_size,
                                                 'repeat_block': neptune_config.parameters.dpcnn_repeat_block,
                                                 'dense_size': neptune_config.parameters.dpcnn_dense_size,
                                                 'repeat_dense': neptune_config.parameters.dpcnn_repeat_dense,
                                                 'l2_reg': neptune_config.parameters.l2_reg_convo,
                                                 'use_prelu': neptune_config.parameters.use_prelu,
                                                 'dropout_convo': neptune_config.parameters.dropout_convo,
                                                 'dropout_dense': neptune_config.parameters.dropout_dense
                                                 },
                                'optimizer_params': {'lr': neptune_config.parameters.lr,
                                                     'momentum': neptune_config.parameters.momentum,
                                                     'nesterov': True
                                                     },
                                },
        'training_config': {'epochs': neptune_config.parameters.epochs_nr,
                            'shuffle': True,
                            'batch_size': neptune_config.parameters.batch_size_train,
                            },
        'callbacks_config': {'model_checkpoint': {
            'filepath': os.path.join(neptune_config.parameters.experiment_dir, 'checkpoints',
                                     'word_dpcnn_network',
                                     'word_dpcnn_network.h5'),
            'save_best_only': True,
            'save_weights_only': False},
            'lr_scheduler': {'gamma': neptune_config.parameters.gamma},
            'early_stopping': {'patience': neptune_config.parameters.patience},
            'neptune_monitor': {},
        },
    },
    'char_cnn_network': {
        'architecture_config': {'model_params': {'max_features': neptune_config.parameters.max_features_char,
                                                 'maxlen': neptune_config.parameters.maxlen_char,
                                                 'embedding_size': neptune_config.parameters.char_embedding_size,
                                                 'filter_nr': neptune_config.parameters.char_cnn_filter_nr,
                                                 'kernel_size': neptune_config.parameters.char_cnn_kernel_size,
                                                 'dense_size': neptune_config.parameters.char_cnn_dense_size,
                                                 'repeat_dense': neptune_config.parameters.char_cnn_repeat_dense,
                                                 'l2_reg': neptune_config.parameters.l2_reg_convo,
                                                 'use_prelu': neptune_config.parameters.use_prelu,
                                                 'dropout_convo': neptune_config.parameters.dropout_convo,
                                                 'dropout_dense': neptune_config.parameters.dropout_dense
                                                 },
                                'optimizer_params': {'lr': neptune_config.parameters.lr,
                                                     },
                                },
        'training_config': {'epochs': neptune_config.parameters.epochs_nr,
                            'batch_size': neptune_config.parameters.batch_size_train,
                            },
        'callbacks_config': {'model_checkpoint': {
            'filepath': os.path.join(neptune_config.parameters.experiment_dir, 'checkpoints',
                                     'char_cnn_network',
                                     'char_cnn_network.h5'),
            'save_best_only': True,
            'save_weights_only': False},
            'lr_scheduler': {'gamma': neptune_config.parameters.gamma},
            'early_stopping': {'patience': neptune_config.parameters.patience},
            'neptune_monitor': {},
        },
        },
    'logistic_regression_multilabel': {'label_nr': 6,
                                       'C': neptune_config.parameters.log_reg_c,
                                       'solver': 'sag',
                                       'n_jobs': neptune_config.parameters.num_workers,
                                       },
    'prediction_average': {'weights': None
                           }
})
