project-key: TOX

name: toxic
tags: [char, vdcnn, adam]


metric:
  channel: 'Final Validation Score ROC_AUC'
  goal: maximize

# Comment out if not in Cloud Environment
pip-requirements-file: requirements.txt

exclude:
  - output
  - imgs
  - neptune.log
  - offline_job.log
  - .git
  - .idea
  - .ipynb_checkpoints

parameters:
# Cloud Environment
  data_dir:                     /public/toxic_comments
  embedding_filepath:           None
  single_model_predictions_dir: /public/toxic_comments/single_model_predictions_20180226
  experiment_dir:               /output/trained_pipelines/char_vdcnn

# Local Environment
#  data_dir:                     /path/to/toxic/data
#  embedding_filepath:           /path/to/embedding i.e. ~/fasttext/crawl-300d-2M.vec
#  single_model_predictions_dir: /path/to/single/model/preds/ i.e. ~/single_model_predictions_20180226
#  experiment_dir:               /my/working/directory i.e. ~/toxic/trained_pipelines/char_vdcnn

  bad_words_filepath: None
  overwrite: 1
  num_workers: 4
  n_cv_splits: 10

# Preprocessing
  max_features_char: 100 # 100 for vdcnn, for tfidf something like 20000 should be used
  max_features_word: None
  maxlen_char: 1000
  maxlen_words: None
  char_ngram_max: None
  drop_punctuation: 0
  drop_newline: 0
  drop_multispaces: 0
  all_lower_case: 1
  fill_na_with: ' '
  deduplication_threshold: 10

# Architecture
  filter_nr: 64
  kernel_size: 3
  repeat_block: 6
  dense_size: 256
  repeat_dense: 2
  max_pooling: 1
  mean_pooling: 1
  weighted_average_attention: 0
  concat_mode: 'concat'
  trainable_embedding: 1
  word_embedding_size: None
  char_embedding_size: 16

# General Architecture
  use_prelu: 1

# Log Reg Params
  log_reg_c: None
  log_reg_penalty: None
  max_iter: None

# Training schedule
  epochs_nr: 1000
  batch_size_train: 128
  batch_size_inference: 128
  lr: 0.005
  momentum: 0.9
  gamma: 0.8
  patience: 10

# Regularization
  batch_norm_first: 1
  use_batch_norm: 1
  dropout_embedding: 0.0
  rnn_dropout: 0.0
  dense_dropout: 0.2
  conv_dropout: 0.2
  dropout_mode: 'spatial'
  rnn_kernel_reg_l2: None
  rnn_recurrent_reg_l2: None
  rnn_bias_reg_l2: None
  dense_kernel_reg_l2: 0.00001
  dense_bias_reg_l2: 0.00001
  conv_kernel_reg_l2: 0.00001
  conv_bias_reg_l2: 0.00001

# Postprocessing
  clipper__lower: None
  clipper__upper: None

# Ensemble Catboost
  catboost__iterations: None
  catboost__learning_rate: None
  catboost__depth: None
  catboost__l2_leaf_reg: None
  catboost__border_count: None
  catboost__model_size_reg: None
  catboost__rsm: None
  catboost__verbose: None

# Ensemble XGBoost
  xgboost__objective: None
  xgboost__eval_metric: None
  xgboost__n_estimators: None
  xgboost__learning_rate: None
  xgboost__max_depth: None
  xgboost__min_child_weight: None
  xgboost__gamma: None
  xgboost__subsample: None
  xgboost__colsample_bytree: None
  xgboost__reg_lambda: None
  xgboost__reg_alpha: None

# Ensemble Blender
  blender__method: None
  blender__runs: None
  blender__maxiter: None
