project-key: TOX

name: toxic
tags: [glove, dpcnn, adam]


metric:
  channel: 'Final Validation Score ROC_AUC'
  goal: maximize

#Comment out if not in Cloud Environment
#pip-requirements-file: requirements.txt

exclude:
  - output
  - imgs
  - neptune.log
  - offline_job.log
  - .git
  - .idea
  - .ipynb_checkpoints

parameters:
  # Cloud Environment
#  data_dir: /public/toxic_comments
#  single_model_predictions_dir: /public/toxic_comments/single_model_predictions_newest
#  experiment_dir: /output/trained_pipelines/glove_dpcnn
#  embedding_filepath: /public/models/glove/glove.840B.300d.txt
  # Local Environment
  data_dir: /mnt/ml-team/minerva/toxic/data
  single_model_predictions_dir: /mnt/ml-team/minerva/toxic/single_model_predictions_newest
  experiment_dir: /mnt/ml-team/minerva/toxic/trained_pipelines/glove_dpcnn
  embedding_filepath: /mnt/ml-team/minerva/pretrained/glove/glove.840B.300d.txt

  bad_words_filepath: None
  overwrite: 1
  num_workers: 4
  n_cv_splits: 5

  # Preprocessing
  max_features_char: None #100 for vdcnn, for tfidf something like 20000 should be used
  max_features_word: 100000
  maxlen_char: None
  maxlen_words: 200
  char_ngram_max: 4
  drop_punctuation: 1
  drop_newline: 1
  drop_multispaces: 1
  all_lower_case: 1
  fill_na_with: ' '
  deduplication_threshold: 10

  # Architecture
  filter_nr: 64
  kernel_size: 3
  repeat_block: 3
  dense_size: 256
  repeat_dense: 1
  max_pooling: 1
  mean_pooling: 0
  weighted_average_attention: 0
  concat_mode: 'concat'
  trainable_embedding: 0
  word_embedding_size: 300
  char_embedding_size: None

  # General Architecture
  use_prelu: 1

 # Log Reg Params
  log_reg_c: None
  log_reg_penalty: None
  max_iter: None

  # Ensemble Catboost
  catboost__iterations: None
  catboost__learning_rate: None
  catboost__depth: None
  catboost__l2_leaf_reg: None
  catboost__border_count: None
  catboost__model_size_reg: None
  catboost__rsm: None
  catboost__verbose: None

  # Training schedule
  epochs_nr: 1000
  batch_size_train: 128
  batch_size_inference: 128
  lr: 0.005
  momentum: 0.9
  gamma: 0.8
  patience: 5

  # Regularization
  batch_norm_first: 1
  use_batch_norm: 1
  dropout_embedding: 0.5
  rnn_dropout: 0.5
  dense_dropout: 0.5
  conv_dropout: 0.2
  dropout_mode: 'spatial'
  rnn_kernel_reg_l2: None
  rnn_recurrent_reg_l2: None
  rnn_bias_reg_l2: None
  dense_kernel_reg_l2: 0.00001
  dense_bias_reg_l2: 0.00001
  conv_kernel_reg_l2: 0.00001
  conv_bias_reg_l2: 0.00001


