project-key: TOX

name: toxic
tags: [setup]


metric:
  channel: 'Final Validation Score ROC_AUC'
  goal: maximize

#Comment out if not in Cloud Environment
#pip-requirements-file: requirements.txt

exclude:
  - output
  - imgs
  - neptune.log
  - offline_job.log
  - .git
  - .idea
  - .ipynb_checkpoints

parameters:
  # Cloud Environment
#  data_dir: /public/toxic_comments
#  single_model_predictions_dir: /public/toxic_comments/single_model_predictions_newest
#  experiment_dir: /output/trained_pipelines
#  embedding_filepath: None
  # Local Environment
  data_dir: /mnt/ml-team/minerva/toxic/data
  single_model_predictions_dir: /mnt/ml-team/minerva/toxic/single_model_predictions_03072018
  experiment_dir: /mnt/ml-team/minerva/toxic/trained_pipelines
  embedding_filepath: None

  bad_words_filepath: None
  overwrite: None
  num_workers: None
  n_cv_splits: None

  # Preprocessing
  max_features_char: None #100 for vdcnn, for tfidf something like 20000 should be used
  max_features_word: None
  maxlen_char: None
  maxlen_words: None
  char_ngram_max: None
  drop_punctuation: None
  drop_newline: None
  drop_multispaces: None
  all_lower_case: None
  fill_na_with: None
  deduplication_threshold: None
  anonymize: 0
  apostrophes: 0
  use_stopwords: 0

  # Architecture
  filter_nr: None
  kernel_size: None
  repeat_block: None
  dense_size: None
  repeat_dense: None
  max_pooling: None
  mean_pooling: None
  weighted_average_attention: None
  concat_mode:  None
  trainable_embedding: None
  word_embedding_size: None
  char_embedding_size: None

  # General Architecture
  use_prelu: None

 # Log Reg Params
  log_reg_c: None
  log_reg_penalty: None
  max_iter: None

  # Training schedule
  epochs_nr: None
  batch_size_train: None
  batch_size_inference: None
  lr: None
  momentum: None
  gamma: None
  patience: None
  unfreeze_on_epoch: None

  # Regularization
  batch_norm_first: None
  use_batch_norm: None
  dropout_embedding: None
  rnn_dropout: None
  dense_dropout: None
  conv_dropout: None
  dropout_mode: None
  rnn_kernel_reg_l2: None
  rnn_recurrent_reg_l2: None
  rnn_bias_reg_l2: None
  dense_kernel_reg_l2: None
  dense_bias_reg_l2: None
  conv_kernel_reg_l2: None
  conv_bias_reg_l2: None

  # Postprocessing
  clipper__lower: None
  clipper__upper: None

  # Ensemble Catboost
  catboost__iterations: None
  catboost__learning_rate: None
  catboost__depth: None
  catboost__l2_leaf_reg: None
  catboost__border_count: None
  catboost__model_size_reg: None
  catboost__rsm: None
  catboost__verbose: None

  # Ensemble XGBoost
  xgboost__objective: None
  xgboost__eval_metric: None
  xgboost__n_estimators: None
  xgboost__learning_rate: None
  xgboost__max_depth: None
  xgboost__min_child_weight: None
  xgboost__gamma: None
  xgboost__subsample: None
  xgboost__colsample_bytree: None
  xgboost__reg_lambda: None
  xgboost__reg_alpha: None

  # Ensemble Blender
  blender__method: None
  blender__runs: None
  blender__maxiter: None
