project-key: TOX

name: toxic
tags: [tfidf, logreg]


metric:
  channel: 'Final Validation Score ROC_AUC'
  goal: maximize

#Comment out if not in Cloud Environment
#pip-requirements-file: requirements.txt

exclude:
  - output
  - imgs
  - neptune.log
  - offline_job.log
  - .git
  - .idea
  - .ipynb_checkpoints

parameters:
  # Cloud Environment
#  data_dir: /public/toxic_comments
#  single_model_predictions_dir: /public/toxic_comments/single_model_predictions_newest
#  experiment_dir: /output/trained_pipelines/tfidf_logreg
#  embedding_filepath: None
  # Local Environment
  data_dir: /mnt/ml-team/minerva/toxic/data
  single_model_predictions_dir: /mnt/ml-team/minerva/toxic/single_model_predictions_newest
  experiment_dir: /mnt/ml-team/minerva/toxic/trained_pipelines/tfidf_logreg
  embedding_filepath: None

  bad_words_filepath: None
  overwrite: 1
  num_workers: 4
  n_cv_splits: 5

  # Preprocessing
  max_features_char: 100000 #100 for vdcnn, for tfidf something like 20000 should be used
  max_features_word: 100000
  maxlen_char: 512
  maxlen_words: 100
  char_ngram_max: 4
  drop_punctuation: 1
  drop_newline: 1
  drop_multispaces: 1
  all_lower_case: 1
  fill_na_with: ' '

  # Architecture
  filter_nr: None
  kernel_size: None
  repeat_block: None
  dense_size: None
  repeat_dense: None
  max_pooling: None
  mean_pooling: None
  weighted_average_attention: None
  concat_mode:  None
  trainable_embedding: None
  word_embedding_size: None
  char_embedding_size: None

  # General Architecture
  use_prelu: None

 # Log Reg Params
  log_reg_c: 1.0
  log_reg_penalty: 'l2'
  max_iter: 1000

  # Ensemble Catboost
  catboost__iterations: None
  catboost__learning_rate: None
  catboost__depth: None
  catboost__l2_leaf_reg: None
  catboost__border_count: None
  catboost__model_size_reg: None
  catboost__rsm: None
  catboost__verbose: None

  # Training schedule
  epochs_nr: None
  batch_size_train: None
  batch_size_inference: None
  lr: None
  momentum: None
  gamma: None
  patience: None

  # Regularization
  batch_norm_first: None
  use_batch_norm: None
  dropout_embedding: None
  rnn_dropout: None
  dense_dropout: None
  conv_dropout: None
  dropout_mode: None
  rnn_kernel_reg_l2: None
  rnn_recurrent_reg_l2: None
  rnn_bias_reg_l2: None
  dense_kernel_reg_l2: None
  dense_bias_reg_l2: None
  conv_kernel_reg_l2: None
  conv_bias_reg_l2: None


